### PR TITLE
Make attributes nullable for the case when `motor_position_at_zero` is empty

### PR DESCRIPTION
**Pull request by kabilar**
- Encountered a case when a ScanImage (version 5.1) TIFF file has an empty `motor_position_at_zero` field in the header.  See snippet below.
```
loaded_scan=scanreader.read_scan(filename)
print(loaded_scan.motor_position_at_zero)
[]
```
- I have made the `x`, `y`, `z`, `field_x`, `field_y`, and `field_z` attributes nullable to handle this case.
- And rename `acq_software` to `acquisition_software`

### CODE REVIEW

**Comment by tdincer** [comment]
Thank you @kabilar! We also need this for nikon files.

**Comment by kabilar** [comment]
Hi @tdincer, how about we review and merge this pull request, and then we can handle the case of motor_position_at_zero being empty for the `NIS` acquisition software in #61?  This can be done by pulling from the base repository on your fork/branch in #61 and then updating `x`, `y`, `z`, `field_x`, `field_y`, and `field_z`.

**Comment by tdincer** [comment]
OK, let's merge this one first. The suggested `PEP-8` variable fix is inconsistent with the primary key of the `AcquisitionSoftware` table defined in Line 120.

**Comment by kabilar** [comment]
Thanks @tdincer.  Good point.  I have reverted the variable name change.

**Comment by tdincer** [comment]
@kabilar Thank you!

**Pull request merged**
