### PR TITLE
bugfix, store output_dir as relative path

### PR DESCRIPTION
**Pull request by ttngu207**

### CODE REVIEW

**Review by CBroz1 — APPROVED** [review]
Looks good to me. I'll hold off on merging until @tdincer has a chance to look. I'm not sure if there are any external readers that rely on an absolute path here

**Comment by tdincer** [comment]
Nevermind the previous comment. But I think `output_dir = cls.infer_output_dir(key, relative=True, mkdir=True)` can easily fix this.

**Comment by ttngu207** [comment]
> Nevermind the previous comment. But I think `output_dir = cls.infer_output_dir(key, relative=True, mkdir=True)` can easily fix this.

Not really, we first need to return the `output_dir` as absolute path so we can then check for existing analysis results (to determine "trigger" or "load")

**Comment by tdincer** [comment]
Right. The loaders take full paths. I totally missed that.

**Review by tdincer — APPROVED** [review]

**Pull request merged**
