### PR TITLE
Bugfix: rename get_image_files to get_calcium_imaging_files

### PR DESCRIPTION
**Pull request by sidhulyalkar**
- Quick fix to change 'get_image_files' function to 'get_calcium_imaging_files' in the infer_output_dir function.

### CODE REVIEW

**Review by kabilar — CHANGES_REQUESTED** [review]
Thanks @sidhulyalkar.  Good catch.  Please update version and changelog.

**Comment by kabilar** [comment]
Please also update the `imaging.py` and `imaging_preprocess.py` modules.

**Comment by sidhulyalkar** [comment]
> Please also update the `imaging.py` and `imaging_preprocess.py` modules.

Updated both imaging.py and imaging_preprocess.py, and the changelog and version are both updated as well.

**Comment by kabilar** [comment]
Please add the following tag to the bottom of the changelog:
```markdown
[0.8.1]: https://github.com/datajoint/element-calcium-imaging/releases/tag/0.8.1
```

**Comment by sidhulyalkar** [comment]
> Please add the following tag to the bottom of the changelog:
> 
> ```
> [0.8.1]: https://github.com/datajoint/element-calcium-imaging/releases/tag/0.8.1
> ```

Just added it 👍🏻

**Review by kabilar — APPROVED** [review]
Thanks @sidhulyalkar!

**Pull request merged**
